sudo: 'required'

language: 'minimal'

services:
  - 'docker'

env:
  - 'VERSION=7.4-fpm-alpine'
  - 'VERSION=7.3-fpm-alpine'
  - 'VERSION=5.6-fpm-alpine'
  - 'VERSION=7.4-fpm'
  - 'VERSION=7.3-fpm'
  - 'VERSION=5.6-fpm'
  - 'VERSION=7.4-alpine'
  - 'VERSION=7.3-alpine'
  - 'VERSION=5.6-alpine'
  - 'VERSION=7.4-apache'
  - 'VERSION=7.3-apache'
  - 'VERSION=5.6-apache'
  - 'VERSION=7.4'
  - 'VERSION=7.3'
  - 'VERSION=5.6'
  - 'VERSION=7.2-fpm-alpine'
  - 'VERSION=7.1-fpm-alpine'
  - 'VERSION=7.0-fpm-alpine'
  - 'VERSION=7.2-fpm'
  - 'VERSION=7.1-fpm'
  - 'VERSION=7.0-fpm'
  - 'VERSION=7.2-alpine'
  - 'VERSION=7.1-alpine'
  - 'VERSION=7.0-alpine'
  - 'VERSION=7.2-apache'
  - 'VERSION=7.1-apache'
  - 'VERSION=7.0-apache'
  - 'VERSION=7.2'
  - 'VERSION=7.1'
  - 'VERSION=7.0'
  - 'VERSION=7-fpm-alpine'
  - 'VERSION=5-fpm-alpine'
  - 'VERSION=7-fpm'
  - 'VERSION=5-fpm'
  - 'VERSION=7-alpine'
  - 'VERSION=5-alpine'
  - 'VERSION=7-apache'
  - 'VERSION=5-apache'
  - 'VERSION=7'
  - 'VERSION=5'
  - 'VERSION=fpm-alpine'
  - 'VERSION=fpm'
  - 'VERSION=alpine'
  - 'VERSION=apache'
  - 'VERSION=latest'

install:
  - 'make build VERSION=${VERSION}'
  - 'make build VERSION=${VERSION} DEV=true'
  
script:
  - 'make test VERSION=${VERSION}'
  - 'make test VERSION=${VERSION} DEV=true'

before_deploy:
  - 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin'

deploy:
  - provider: 'script'
    script: 'make push VERSION=${VERSION}'
    on:
      repo: 'm0bua/docker-php'
      branch: 'master'
  - provider: 'script'
    script: 'make push VERSION=${VERSION} DEV=true'
    on:
      repo: 'm0bua/docker-php'
      branch: 'master'